"""added parent issue id in issue table

Revision ID: 0b6d4b1b92ed
Revises: 9b2722596c18
Create Date: 2025-12-30 17:10:39.181960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b6d4b1b92ed'
down_revision: Union[str, None] = '9b2722596c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('parent_issue_id', sa.Integer(), nullable=True))
    op.alter_column('issue', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='priority'),
               nullable=True)
    op.create_foreign_key(None, 'issue', 'issue', ['parent_issue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.alter_column('issue', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='priority'),
               nullable=False)
    op.drop_column('issue', 'parent_issue_id')
    # ### end Alembic commands ###
