"""updated/added models

Revision ID: 2eed5761779a
Revises: b7cf6194f454
Create Date: 2025-12-25 17:36:03.774972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eed5761779a'
down_revision: Union[str, None] = 'b7cf6194f454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='organization_enum'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='u_org_user')
    )
    op.add_column('project', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project', 'organization', ['organization_id'], ['id'])
    op.add_column('project_member', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_constraint('u_project_user', 'project_member', type_='unique')
    op.create_unique_constraint('u_org_project_user', 'project_member', ['organization_id', 'project_id', 'user_id'])
    op.create_foreign_key(None, 'project_member', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_member', type_='foreignkey')
    op.drop_constraint('u_org_project_user', 'project_member', type_='unique')
    op.create_unique_constraint('u_project_user', 'project_member', ['project_id', 'user_id'])
    op.drop_column('project_member', 'organization_id')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'organization_id')
    op.drop_table('organization_member')
    op.drop_table('organization')
    # ### end Alembic commands ###
