"""add_project_id_to_issue

Revision ID: 3963f59375ee
Revises: cd7ac4bb0300
Create Date: 2025-12-27 20:37:22.303250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3963f59375ee'
down_revision: Union[str, None] = 'cd7ac4bb0300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('issue', sa.Column('project_id', sa.Integer(), nullable=True))
    
    # Step 2: Update existing issues to set project_id from sprint.project_id
    op.execute("""
        UPDATE issue 
        SET project_id = (
            SELECT sprint.project_id 
            FROM sprint 
            WHERE sprint.id = issue.sprint_id
        )
        WHERE sprint_id IS NOT NULL
    """)
    
    # Step 3: For issues without sprint, we need to handle them
    # If there are any remaining NULL values, we'll need to set a default or handle them
    # For now, let's make it nullable=False after setting defaults
    # If you have issues without sprints, you may need to set a default project_id
    
    # Step 4: Make column NOT NULL (only if all rows have project_id)
    op.alter_column('issue', 'project_id', nullable=False)
    
    # Step 5: Create foreign key constraint
    op.create_foreign_key('issue_project_id_fkey', 'issue', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issue_project_id_fkey', 'issue', type_='foreignkey')
    op.drop_column('issue', 'project_id')
    # ### end Alembic commands ###
