"""Switch enums to use .value defaults

Revision ID: 507cd0d55963
Revises: 0b6d4b1b92ed
Create Date: 2025-12-31 22:35:07.548453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507cd0d55963'
down_revision: Union[str, None] = '0b6d4b1b92ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
