"""add priority field to issue

Revision ID: cd7ac4bb0300
Revises: 2eed5761779a
Create Date: 2025-12-27 20:26:58.171948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd7ac4bb0300'
down_revision: Union[str, None] = '2eed5761779a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: project_id is NOT added - issues are linked to projects through sprints
    # Priority field already exists in database, just ensuring it's NOT NULL
    conn = op.get_bind()
    
    # Helper function to check if index exists
    def index_exists(index_name, table_name):
        result = conn.execute(sa.text(
            "SELECT 1 FROM pg_indexes WHERE indexname = :index_name AND tablename = :table_name"
        ), {"index_name": index_name, "table_name": table_name})
        return result.fetchone() is not None
    
    # First, update all NULL priority values to 'MODERATE' (default, uppercase for database enum)
    op.execute(sa.text(
        "UPDATE issue SET priority = 'MODERATE' WHERE priority IS NULL"
    ))
    
    # Now alter priority column to be NOT NULL
    op.alter_column('issue', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='priority'),
               nullable=False)
    
    # Create indexes only if they don't exist
    if not index_exists('idx_issue_assigned_by', 'issue'):
        op.create_index('idx_issue_assigned_by', 'issue', ['assigned_by'], unique=False)
    if not index_exists('idx_issue_assigned_to', 'issue'):
        op.create_index('idx_issue_assigned_to', 'issue', ['assigned_to'], unique=False)
    if not index_exists('idx_issue_sprint_id', 'issue'):
        op.create_index('idx_issue_sprint_id', 'issue', ['sprint_id'], unique=False)
    if not index_exists('idx_issue_status', 'issue'):
        op.create_index('idx_issue_status', 'issue', ['status'], unique=False)
    if not index_exists('idx_issue_type', 'issue'):
        op.create_index('idx_issue_type', 'issue', ['type'], unique=False)
    
    # Other indexes for other tables
    if not index_exists('idx_org_status', 'organization'):
        op.create_index('idx_org_status', 'organization', ['status'], unique=False)
    if not index_exists('idx_project_created_by', 'project'):
        op.create_index('idx_project_created_by', 'project', ['created_by'], unique=False)
    if not index_exists('idx_project_status', 'project'):
        op.create_index('idx_project_status', 'project', ['status'], unique=False)
    if not index_exists('idx_user_role', 'user'):
        op.create_index('idx_user_role', 'user', ['role'], unique=False)
    if not index_exists('idx_user_status', 'user'):
        op.create_index('idx_user_status', 'user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Helper function to check if index exists
    def index_exists(index_name, table_name):
        result = conn.execute(sa.text(
            "SELECT 1 FROM pg_indexes WHERE indexname = :index_name AND tablename = :table_name"
        ), {"index_name": index_name, "table_name": table_name})
        return result.fetchone() is not None
    
    # Drop indexes only if they exist
    if index_exists('idx_user_status', 'user'):
        op.drop_index('idx_user_status', table_name='user')
    if index_exists('idx_user_role', 'user'):
        op.drop_index('idx_user_role', table_name='user')
    if index_exists('idx_project_status', 'project'):
        op.drop_index('idx_project_status', table_name='project')
    if index_exists('idx_project_created_by', 'project'):
        op.drop_index('idx_project_created_by', table_name='project')
    if index_exists('idx_org_status', 'organization'):
        op.drop_index('idx_org_status', table_name='organization')
    if index_exists('idx_issue_type', 'issue'):
        op.drop_index('idx_issue_type', table_name='issue')
    if index_exists('idx_issue_status', 'issue'):
        op.drop_index('idx_issue_status', table_name='issue')
    if index_exists('idx_issue_sprint_id', 'issue'):
        op.drop_index('idx_issue_sprint_id', table_name='issue')
    if index_exists('idx_issue_assigned_to', 'issue'):
        op.drop_index('idx_issue_assigned_to', table_name='issue')
    if index_exists('idx_issue_assigned_by', 'issue'):
        op.drop_index('idx_issue_assigned_by', table_name='issue')
    
    op.alter_column('issue', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='priority'),
               nullable=True)
    # Note: project_id was never added, so no need to drop it
    # ### end Alembic commands ###
